feat: mongodb arbiter

diff --git a/kubernetes/mongodb-rs/configmap.yaml b/kubernetes/mongodb-rs/configmap.yaml
--- a/kubernetes/mongodb-rs/configmap.yaml
+++ b/kubernetes/mongodb-rs/configmap.yaml
@@ -1,8 +1,8 @@
-# mongodb-startup-script.yaml
+# mongodb-script.yaml
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: mongodb-startup-script
+  name: mongodb-script
   namespace: yasin-app
 data:
   startup.sh: |
@@ -18,3 +18,79 @@ data:
     fi
 
     exec /opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh
+
+  check-replicaset.sh: |
+    #!/bin/bash
+    
+    MAX_ATTEMPTS=30
+    SLEEP_TIME=5
+    REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-rs0}
+    
+    wait_for_mongodb() {
+      local host=${1}
+      local attempt=1
+      while [ ${attempt} -le ${MAX_ATTEMPTS} ]; do
+        echo "Try #${attempt}: connect to ${host}"
+        if mongo --host ${host} -u${MONGODB_INITIAL_PRIMARY_ROOT_USER} -p${MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD} --quiet --eval "db.adminCommand({ping:1})" > /dev/null 2>&1; then
+          return 0
+        fi
+        sleep ${SLEEP_TIME}
+        attempt=$((attempt + 1))
+      done
+      return 1
+    }
+    
+    check_replica_set_health() {
+      local host=${1}
+      local health_status=$(mongo --host ${host} -u${MONGODB_INITIAL_PRIMARY_ROOT_USER} -p${MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD} --quiet --eval "
+        const status = rs.status();
+        if (status.ok !== 1) {
+          print('REPLICASET_NOT_OK');
+          quit(1);
+        }
+    
+        const totalMembers = status.members.length;
+        const healthyMembers = status.members.filter(m => m.health === 1).length;
+        const primaryMembers = status.members.filter(m => m.stateStr === 'PRIMARY').length;
+        const secondaryMembers = status.members.filter(m => m.stateStr === 'SECONDARY').length;
+    
+        print('TOTAL:' + totalMembers);
+        print('HEALTHY:' + healthyMembers);
+        print('PRIMARY:' + primaryMembers);
+        print('SECONDARY:' + secondaryMembers);
+    
+        if (healthyMembers < Math.ceil(totalMembers - 1) / 2 + 1) {
+         print('NOT_ENOUGH_HEALTHY_MEMBERS');
+         quit(1);
+        }
+    
+        print('REPLICASET_HEALTHY');
+      " 2>/dev/null)
+    
+      echo "${health_status}"
+      return 0
+    }
+    
+    echo "Start checking MongoDB replica set health status"
+    for i in $(seq 0 $((REPLICAS_COUNT-1))); do
+      host="mongodb-${i}.mongodb-headless:27017"
+      if wait_for_mongodb "${host}"; then
+        echo "Connect to ${host}"
+        echo "Check replica set status..."
+    
+        health_output=$(check_replica_set_health "${host}")
+    
+        if echo "${health_output}" | grep -q "REPLICASET_HEALTHY"; then
+          echo "✓ MongoDB replica set health"
+    
+          echo "${health_output}" | grep -E "^(TOTAL|HEALTHY|PRIMARY|SECONDARY):"
+          exit 0
+        else
+          echo "MongoDB Replica set status is unhealthy::"
+          echo "${health_output}"
+        fi
+      fi
+    done
+    
+    echo "✗ Unable to connect to healthy MongoDB replica set"
+    exit 1
